spring.application.name=Gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Debug
logging.level.org.springframework.cloud.gateway=DEBUG

# Criatura
spring.cloud.gateway.server.webflux.routes[0].id=criatura-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://Criatura
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/criatura/**

# Usuario
spring.cloud.gateway.server.webflux.routes[1].id=usuario-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://Usuario
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/usuarios/**

# Acceso
spring.cloud.gateway.server.webflux.routes[2].id=acceso-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://Acceso
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/accesos/**

# Elemento
spring.cloud.gateway.server.webflux.routes[3].id=elemento-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://Elemento
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/elementos/**

# Habilidad
spring.cloud.gateway.server.webflux.routes[4].id=habilidad-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://Habilidad
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/habilidad/**

# Habitat
spring.cloud.gateway.server.webflux.routes[5].id=habitat-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://Habitat
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/habitat/**

# Rareza
spring.cloud.gateway.server.webflux.routes[6].id=rareza-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://Rareza
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/rareza/**

# TipoCriatura
spring.cloud.gateway.server.webflux.routes[7].id=tipocriatura-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://TipoCriatura
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/tipo-criatura/**

# Comentario
spring.cloud.gateway.server.webflux.routes[8].id=comentario-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://comentario
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/v1/comentarios/**

# Favorito
spring.cloud.gateway.server.webflux.routes[9].id=favorito-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://favorito
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/v1/favoritos/**

# CriaturaElemento
spring.cloud.gateway.server.webflux.routes[10].id=criaturaelemento-service
spring.cloud.gateway.server.webflux.routes[10].uri=lb://CriaturaElemento
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/v1/criatura-elementos/**

# CriaturaHabitat
spring.cloud.gateway.server.webflux.routes[11].id=criaturahabitat-service
spring.cloud.gateway.server.webflux.routes[11].uri=lb://CriaturaHabitat
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/v1/criatura-habitats/**